### ISSUE TITLE
Nellie Potter 

### ISSUE THREAD

**Issue by ststimac** [webhintio/artwork#1]
A Harry Potter themed Nellie -- I'd like to use this one on the website while users are waiting for the scanner to finish scanning. 

Would like to do some animation during the wait, something simple like waving a wand with sparks coming out of it.

**Comment by molant** [comment]
> Would like to do some animation during the wait, something simple like waving a wand with sparks coming out of it.

Not a Expecto Patronum? 😟

**Comment by ststimac** [comment]
let's shoot for that in a v2

**Comment by alrra** [comment]
Closing for now, but maybe we will do this in the future.
